title: International Press book series ICCMP author support
description: TeX related material for the manuscript preparation for the 
             International Press book series Proceedings of the International Congress of Chinese Mathematicians
             (ICCMP)
show_downloads: true
theme: jekyll-theme-tactile
